version: "3.8"

services:
  # Redis Cache for Development
  redis:
    image: redis:7.2-alpine
    container_name: black-market-redis-dev
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_dev_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  redis_dev_data:
    driver: local
